---
title: "Coffee Cup"
type: "exercise"
description: "Model a coffee cup with a Ruby class"
tags: "class, initialize, objects, constructors, state, behavior, instance methods"
visibility: "subscribe"
---
